version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install ".[docs]"
    - |
      fqr docs . \
        --index-from-readme \
        --include-private-modules \
        --author dan@1howardcapital.com \
        --version $(fqr --version) \
        --site-map-url https://fqr.readthedocs.io/en/latest
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r docs/html/ $READTHEDOCS_OUTPUT
