name: 'Check Files'
description: 'Check files.'
inputs:
  token:
    description: GITHUB_TOKEN
    required: true
outputs:
  is_semantic_release_required:
    description: 'Whether or not a semantic release should take place.'
  is_testing_required:
    description: 'Whether or not tests should take place.'
runs:
  using: 'node20'
  main: 'index.js'