name: main

permissions:
  id-token: write

on:
  pull_request:
    branches:
      - main
    paths:
      - '!**/*'
      - './pyproject.toml'
      - './src/fqr/__init__.py'
  push:
    branches:
      - main
    paths:
      - '!**/*'
      - './pyproject.toml'
      - './src/fqr/__init__.py'

jobs:
  release:
    needs: [setup, lint, test]
    name: semantic release
    runs-on: ubuntu-latest
    concurrency: push
    if: github.repository == 'dan1hc/fqr'
    environment:
      name: pypi
      url: https://pypi.org/p/fqr
    permissions:
      actions: write
      contents: write
      deployments: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'push' && github.ref_name || github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: semantic release
        id: release
        uses: python-semantic-release/python-semantic-release@master
        with:
          changelog: ${{ github.event_name == 'push' }}
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          prerelease: ${{ github.event_name == 'pull_request' }}
      - name: publish pypi
        id: pypi-publish
        if: steps.release.outputs.released == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
      - name: publish github release
        id: github-release
        if: steps.release.outputs.released == 'true'
        uses: python-semantic-release/upload-to-gh-release@main
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
