name: main

permissions:
  id-token: write

on:
  pull_request:
    branches:
      - main
    paths:
      - '!**/*'
      - '**/*.py'
      - '!./src/fqr/__init__.py'
  push:
    branches:
      - main
    paths:
      - '!**/*'
      - '**/*.py'
      - '!./src/fqr/__init__.py'

env:
  PY_VERSIONS: "[\"3.12\",\"3.11\",\"3.10\"]"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: install-npm-deps
        run: npm i @actions/core @actions/github
      - id: validate-commit-message
        uses: ./.github/actions/validate-commit-message
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  setup:
    needs: validate
    runs-on: ubuntu-latest
    if: always() && !failure() && !cancelled()
    outputs:
      python-versions: ${{ steps.setVariables.outputs.python-versions }}
    steps:
      - id: setVariables
        run: |
          echo "python-versions=${{ toJson(env.PY_VERSIONS) }}" >> $GITHUB_OUTPUT
  lint:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python Latest
        uses: actions/setup-python@v5
        with:
          python-version: ${{ fromJson(env.PY_VERSIONS)[0] }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install deps
        run: |
          python -m pip install ".[develop]"
      - name: ruff
        run: |
          python -m ruff check . \
            --config pyproject.toml \
            --diff \
            --show-files \
            --exit-non-zero-on-fix
  test:
    needs: [setup, lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.setup.outputs.python-versions) }}
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup dependencies
        run: |
          python -m pip install ".[develop]"
      - name: mypy
        run: python -m mypy
      - name: pytest
        run: pytest --verbose
